# Generated by Django 3.1.1 on 2020-09-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='files',
            new_name='File',
        ),
    ]
